export const sample_foods = [
  {
    id: '1',
    name: 'cơm tấm',
    cookTime: '10-20',
    price: 30000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['cơm'],
  },
  {
    id: '2',
    name: 'cơm gà xối mỡ',
    cookTime: '10-20',
    price: 30000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-2.jpg',
    tags: ['cơm'],
  },
  {
    id: '3',
    name: 'cơm phần',
    cookTime: '10-20',
    price: 30000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-3.jpg',
    tags: ['cơm'],
  },
  {
    id: '4',
    name: 'cơm trắng',
    cookTime: '10-20',
    price: 5000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-4.jpg',
    tags: ['cơm'],
  },
  {
    id: '5',
    name: 'hủ tiếu',
    cookTime: '10-20',
    price: 25000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-5.jpg',
    tags: ['món nước'],
  },
  {
    id: '6',
    name: 'phở',
    cookTime: '10-20',
    price: 35000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-6.jpg',
    tags: ['món nước'],
  },
  {
    id: '7',
    name: 'bún bò',
    cookTime: '10-20',
    price: 35000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-7.jpg',
    tags: ['món nước'],
  },
  {
    id: '8',
    name: 'bún riêu',
    cookTime: '10-20',
    price: 30000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-8.jpg',
    tags: ['món nước'],
  },
  {
    id: '9',
    name: 'chân gà sốt thái',
    cookTime: '10-20',
    price: 60000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-9.jpg',
    tags: ['ăn vặt'],
  },
  {
    id: '10',
    name: 'tré trộn',
    cookTime: '10-20',
    price: 45000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-10.jpg',
    tags: ['ăn vặt'],
  },
  {
    id: '11',
    name: 'bánh tráng nướng',
    cookTime: '10-20',
    price: 15000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-11.jpg',
    tags: ['ăn vặt'],
  },
  {
    id: '12',
    name: 'cơm cháy',
    cookTime: '10-20',
    price: 30000,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-12.jpg',
    tags: ['ăn vặt'],
  },
];

export const sample_tags = [
  { name: 'All', count: 12 },
  { name: 'cơm', count: 4 },
  { name: 'món nước', count: 4 },
  { name: 'ăn vặt', count: 4 },
];

export const sample_users = [
  {
    id: 1,
    name: 'admin',
    email: 'admin@gmail.com',
    password: '12345',
    address: 'UIT',
    isAdmin: true,
  },
  
];